---
collections:
  - name: community.kubernetes
    version: "<1.2.2"
  - name: operator_sdk.util
    version: "0.4.0"
  - name: kubernetes.core
    version: ">=2.2.0,<3.0.0"
  - name: cloud.common
    version: "2.1.1"
  - name: ibm.cloudcollection
    version: ">=1.37.1,<2.0.0"
  - ibm.mas_devops
