apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: masauto-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: masauto-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
