apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "AppCon",
          "metadata": {
            "name": "masauto-appcon",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "appconnect_storage_class": "ocs-storagecluster-cephfs",
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_instance_id": "inst1"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "CP4D",
          "metadata": {
            "name": "masauto-cp4d-foundation",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "cpd_metadata_storage_class": "ibmc-vpcblock-odf-10iops",
            "cpd_primary_storage_class": "ocs-storagecluster-cephfs",
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "install_analytics_engine": "false",
            "install_cp4d_platform": "true",
            "install_watson_discovery": "false",
            "install_watson_machine_learning": "false",
            "install_watson_openscale": "false",
            "install_watson_studio": "false"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "CP4D",
          "metadata": {
            "name": "masauto-cp4d-wsl",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "cpd_metadata_storage_class": "ibmc-vpcblock-odf-10iops",
            "cpd_primary_storage_class": "ocs-storagecluster-cephfs",
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "install_analytics_engine": "false",
            "install_cp4d_platform": "false",
            "install_watson_discovery": "false",
            "install_watson_machine_learning": "false",
            "install_watson_openscale": "false",
            "install_watson_studio": "true",
            "mas_instance_id": "inst1"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "Core",
          "metadata": {
            "name": "masauto-core",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_channel": "8.8.x",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev",
            "mas_workspace_name": "MAS Development",
            "mongodb_storage_class": "ibmc-vpcblock-odf-10iops",
            "uds_contact": {
              "email": "tskill@us.ibm.com",
              "first_name": "tom",
              "last_name": "skill"
            },
            "uds_storage_class": "ibmc-vpcblock-odf-10iops"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "HPU",
          "metadata": {
            "name": "masauto-hpu",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_app_channel": "8.4.x",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "IoT",
          "metadata": {
            "name": "masauto-iot",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "db2_data_storage_class": "ibmc-vpcblock-odf-10iops",
            "db2_instance_name": "db2w-shared",
            "db2_meta_storage_class": "ocs-storagecluster-cephfs",
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "kafka_storage_class": "ibmc-vpcblock-odf-10iops",
            "mas_app_channel": "8.5.x",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "Manage",
          "metadata": {
            "name": "masauto-manage",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "db2_data_storage_class": "ibmc-vpcblock-odf-10iops",
            "db2_instance_name": "db2w-shared",
            "db2_meta_storage_class": "ocs-storagecluster-cephfs",
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_app_channel": "8.4.x",
            "mas_app_id": "manage",
            "mas_app_settings_demodata": "true",
            "mas_appws_components": "{\"base\":{\"version\":\"latest\"},\"health\":{\"version\":\"latest\"}}",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "Monitor",
          "metadata": {
            "name": "masauto-monitor",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_app_channel": "8.8.x",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev"
          }
        },
        {
          "annotations": {
            "ansible.operator-sdk/reconcile-period": "0s"
          },
          "apiVersion": "masauto.ibm.com/v1alpha1",
          "kind": "Predict",
          "metadata": {
            "name": "masauto-predict",
            "namespace": "masauto-operator-system"
          },
          "spec": {
            "ibm_entitlement_secret": "ibm-entitlement-key",
            "mas_app_channel": "8.6.x",
            "mas_instance_id": "inst1",
            "mas_workspace_id": "masdev"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.0-ocp
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: masauto-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AppCon
      name: appcons.masauto.ibm.com
      version: v1alpha1
    - kind: Core
      name: cores.masauto.ibm.com
      version: v1alpha1
    - kind: CP4D
      name: cp4ds.masauto.ibm.com
      version: v1alpha1
    - kind: HPU
      name: hpus.masauto.ibm.com
      version: v1alpha1
    - kind: IoT
      name: iots.masauto.ibm.com
      version: v1alpha1
    - kind: Manage
      name: manages.masauto.ibm.com
      version: v1alpha1
    - kind: Masauto
      name: masautoes.masauto.ibm.com
      version: v1alpha1
    - kind: Monitor
      name: monitors.masauto.ibm.com
      version: v1alpha1
    - kind: Predict
      name: predicts.masauto.ibm.com
      version: v1alpha1
  description: This operator will install all components of the Maximo App Suite (MAS).
  displayName: Maximo App Suite Automation
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: masauto-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: masauto-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.11
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=masauto-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: docker.io/tcskill/masauto:v0.10.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: masauto-operator-controller-manager
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Maximo
  - MAS
  links:
  - name: Masauto Operator
    url: https://masauto-operator.domain
  maintainers:
  - email: tskill@us.ibm.com
    name: Tom Skill
  - email: seansund@us.ibm.com
    name: Sean Sundberg
  maturity: alpha
  provider:
    name: IBM Ecosystem Engineering
    url: https://modules.cloudnativetoolkit.dev/
  version: 0.0.1
