    # Checks for CR install status of Ready in True state and ends play if true
    - name: "Check Ready status of CR"
      kubernetes.core.k8s_info:
        api_version: masauto.ibm.com/v1alpha1
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        kind: "{{ cr_kind }}"
      register: cr_instance_lookup

    - name: "End play if ready is True for CR"
      when: (cr_instance_lookup.resources[0].status.Ready is defined) and
            (cr_instance_lookup.resources[0].status.Ready == "True")
      meta: end_play      

    # Install isn't completed so set Ready status to False for CR
    - name: "Set CR status of Ready to false when not completed"
      k8s_status:
        api_version: masauto.ibm.com/v1alpha1
        kind: "{{ cr_kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          Ready: "False"