    # Check if optimizer is already installed first.
    - name: "Check for Optimizer already installed"
      kubernetes.core.k8s_info:
        api_version: apps.mas.ibm.com/v1
        kind: OptimizerWorkspace
        name: "{{ mas_instance_id }}-{{ mas_workspace_id }}"
        namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
      register: op_app_ws_cr_result

    # End the play if it's in Ready state.
    - name: "Check if all components are deployed and Ready"
      when: (op_app_ws_cr_result.resources is defined) and
            (op_app_ws_cr_result.resources | length > 0) and
            (op_app_ws_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1)
      meta: end_play