    ## Check if Assist App is instlaled and activate is false
    ## this will be removed when product ansible is fixed for
    ## objectstorage cfg.
    - name: "Check for Assist App already installed"
      when: not (activate_app|bool)
      kubernetes.core.k8s_info:
        api_version: apps.mas.ibm.com/v1
        kind: AssistApp
        name: "{{ mas_instance_id }}"
        namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
      register: op_app_ap_cr_result

    ## End the play if it's in Ready state.
    ## Remove when obectstorage cfg fixed.
    - name: "Check if all components are deployed and Ready"
      when: not (activate_app|bool) and
            (op_app_ap_cr_result.resources is defined) and
            (op_app_ap_cr_result.resources | length > 0) and
            (op_app_ap_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1)
      meta: end_play  


    # Check if Assist is already installed first.
    - name: "Check for Asstst already installed"
      kubernetes.core.k8s_info:
        api_version: apps.mas.ibm.com/v1
        kind: AssistWorkspace
        name: "{{ mas_instance_id }}-{{ mas_workspace_id }}"
        namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
      register: op_app_ws_cr_result

    # End the play if it's in Ready state.
    - name: "Check if all components are deployed and Ready"
      when: (op_app_ws_cr_result.resources is defined) and
            (op_app_ws_cr_result.resources | length > 0) and
            (op_app_ws_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1)
      meta: end_play