# permissions for end users to view appcons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appcon-viewer-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - appcons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - appcons/status
  verbs:
  - get
