# permissions for end users to edit assists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assist-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - assists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - assists/status
  verbs:
  - get
