# permissions for end users to edit cp4ds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cp4d-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - cp4ds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - cp4ds/status
  verbs:
  - get
