# permissions for end users to edit hpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpu-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - hpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - hpus/status
  verbs:
  - get
