# permissions for end users to view hpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpu-viewer-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - hpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - hpus/status
  verbs:
  - get
