# permissions for end users to edit iots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iot-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - iots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - iots/status
  verbs:
  - get
