# permissions for end users to view iots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iot-viewer-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - iots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - iots/status
  verbs:
  - get
