# permissions for end users to edit masautoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: masauto-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - masautoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - masautoes/status
  verbs:
  - get
