# permissions for end users to view optimizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimizer-viewer-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - optimizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - optimizers/status
  verbs:
  - get
