# permissions for end users to edit predicts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: predict-editor-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - predicts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - predicts/status
  verbs:
  - get
