# permissions for end users to view predicts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: predict-viewer-role
rules:
- apiGroups:
  - masauto.ibm.com
  resources:
  - predicts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - masauto.ibm.com
  resources:
  - predicts/status
  verbs:
  - get
