apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: ibm-common-services
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: grafana
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mongoce  
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: ibm-sls
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mas-inst1-core
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mas-inst1-manage
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mas-inst1-health
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mas-inst1-iot
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: mas-inst1-monitor    
- kind: ServiceAccount
  name: masauto-operator-controller-manager
  namespace: ibm-app-connect

