## Append samples you want in your CSV to this file as resources ##
resources:
- sample_core_dr.yaml
- sample_manage_cr.yaml
- sample_iot_cr.yaml
- sample_appcon_cr.yaml
- sample_cp4d_cr.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
