apiVersion: masauto.ibm.com/v1alpha1
kind: CP4D
metadata:
  name: masauto-cp4d-wsl
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key"
  cpd_primary_storage_class: "ocs-storagecluster-cephfs"
  cpd_metadata_storage_class: "ocs-storagecluster-ceph-rbd"
  cpd_product_version: "4.6.3"
  cpd_instance_namespace: "ibm-cpd"
  install_cp4d_platform: "false"

  install_watson_studio: "true"
  mas_instance_id: "inst1"

  install_watson_machine_learning: "false"
  install_analytics_engine: "false"
  install_watson_openscale: "false"
  install_watson_discovery: "false"
  install_spss_modeler: "false"