apiVersion: masauto.ibm.com/v1alpha1
kind: Manage
metadata:
  name: masauto-manage
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"    
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  configure_external_db: "false"
  db2_instance_name: "db2w-manage"
  mas_app_id: "manage"
  mas_app_channel: "8.5.x"
  db2_memory_requests: "3Gi"
  db2_database_db_config: {
    LOGARCHMETH1: "OFF"
  }
  db2_dbname: "MANAGE"
  mas_config_scope: "wsapp"  # recommend keeping db for manage at workspace-application scope by default
  mas_appws_bindings_jdbc: "workspace-application"
  db2_meta_storage_class: "ocs-storagecluster-cephfs"
  db2_data_storage_class: "ocs-storagecluster-ceph-rbd"
  mas_app_settings_demodata: "true"
  mas_appws_components:
    base:
      version: latest
    health:
      version: latest