apiVersion: masauto.ibm.com/v1alpha1
kind: HPU
metadata:
  name: masauto-hpu
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.6.x"