apiVersion: masauto.ibm.com/v1alpha1
kind: Manage
metadata:
  name: masauto-manage
spec:
  ibm_entitlement_key: "eyJhbGciOiJIUzI1NiJ9........YOUR key goes here"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  db2_instance_name: "db2w-shared"
  mas_app_id: "manage"
  mas_app_channel: "8.4.x"
  db2_meta_storage_class: "ocs-storagecluster-cephfs"
  db2_data_storage_class: "ibmc-vpcblock-odf-10iops"
  mas_appws_components: "{\"base\":{\"version\":\"latest\"},\"health\":{\"version\":\"latest\"}}"
  mas_app_settings_demodata: "true"
  