apiVersion: masauto.ibm.com/v1alpha1
kind: Manage
metadata:
  name: masauto-manage
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"    
spec:
  ibm_entitlement_secret: "ibm-entitlement-key"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_id: "manage"
  mas_app_channel: "8.6.x"
  configure_external_db: "true"
  ssl_enabled: true
  db_pem_configmap: "ca-pemstore"

  db_instance_id: "db2w-manage"
  mas_jdbc_user: "db2inst1"
  mas_jdbc_password_secret: "manage-jdbc-credentials"
  mas_jdbc_url: "<your_jdbc_url_see_examples>"

  mas_app_settings_db2_schema: "MANAGE"
  mas_app_settings_tablespace: "MAXDATA"
  mas_app_settings_indexspace: "MAXINDEX"

  mas_config_scope: "wsapp"
  mas_appws_bindings_jdbc: "workspace-application"

  mas_app_settings_demodata: "true"
  mas_appws_components:
    base:
      version: latest
    health:
      version: latest