apiVersion: masauto.ibm.com/v1alpha1
kind: Predict
metadata:
  name: masauto-predict
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.8.x"
  cpd_product_version: "4.6.3"
  cpd_instance_namespace: "ibm-cpd"
  mas_appws_settings_deployment_size: "developer"