apiVersion: masauto.ibm.com/v1alpha1
kind: IoT
metadata:
  name: masauto-iot
spec:
  ibm_entitlement_key: "eyJhbGciOiJIUzI1NiJ9........YOUR key goes here"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  db2_instance_name: "db2w-shared"
  mas_app_id: "iot"
  mas_app_channel: "8.4.x"
  db2_meta_storage_class: "ocs-storagecluster-cephfs"
  db2_data_storage_class: "ibmc-vpcblock-odf-10iops"
  kafka_storage_class: "ibmc-vpcblock-odf-10iops"
