apiVersion: masauto.ibm.com/v1alpha1
kind: Monitor
metadata:
  name: masauto-monitor
spec:
  ibm_entitlement_key: "eyJhbGciOiJIUzI1NiJ9........YOUR key goes here"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.8.x"
