# Adds Predict latest release to an existing MAS v8.8.x installation
#
# Predict will be deployed and configured. Note this app has several dependencies
#
# Dependencies:
# - CP4D Foundation
# - CP4D Services: wsl, wml, spark, aiopenscale
# - Maximo Monitor
# - Maximo Health
#
apiVersion: masauto.ibm.com/v1alpha1
kind: Predict
metadata:
  name: masauto-predict
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.6.x"
