apiVersion: masauto.ibm.com/v1alpha1
kind: Predict
metadata:
  name: masauto-predict
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.7.x"
  cpd_product_version: "4.5.2"
  cpd_url: "<https:// ... insert your cp4d_url>"
