# Adds HP&U latest release to an existing MAS Core 8.9.x 
#
# Dependencies:
# - Core is installed
# - Health is installed
# - CP4D/WSL
# - AppConnect
#
apiVersion: masauto.ibm.com/v1alpha1
kind: HPU
metadata:
  name: masauto-hpu
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.5.x"
