apiVersion: masauto.ibm.com/v1alpha1
kind: CP4D
metadata:
  name: masauto-cp4d-foundation
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace
  cpd_primary_storage_class: "ocs-storagecluster-cephfs" # file
  cpd_metadata_storage_class: "ibmc-vpcblock-odf-10iops" # block
