apiVersion: masauto.ibm.com/v1alpha1
kind: IoT
metadata:
  name: masauto-iot
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"    
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace
  mas_instance_id: "inst1"
  mas_app_channel: "8.6.x"
  mas_workspace_id: "masdev"
  db2_instance_name: "db2w-iot"
  db2_dbname: "MASIOT"
  db2_meta_storage_class: "ocs-storagecluster-cephfs"
  db2_data_storage_class: "ibmc-vpcblock-odf-10iops"
  kafka_storage_class: "ibmc-vpcblock-odf-10iops"
  grafana_instance_storage_class: "ocs-storagecluster-cephfs"
  prometheus_alertmgr_storage_class: "ocs-storagecluster-cephfs"
  prometheus_storage_class: "ocs-storagecluster-cephfs"
  zookeeper_storage_class: "ibmc-vpcblock-odf-10iops"
  