apiVersion: masauto.ibm.com/v1alpha1
kind: AppCon
metadata:
  name: masauto-appcon
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_key_secret: "ibm-entitlement-key"
  mas_instance_id: "inst1"
  appconnect_storage_class: "ocs-storagecluster-cephfs" #file storage class
