apiVersion: masauto.ibm.com/v1alpha1
kind: Assist
metadata:
  name: masauto-assist
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key"
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.7.x"
  cos_type: "ocs"
  cpd_product_version: "4.6.3"
  cpd_instance_namespace: "ibm-cpd"
  activate_app: "false"