# Adds Monitor latest release to an existing MAS Core 8.9.x + IoT 8.6.x installation
#
# Monitor will be configured to use the same db2 instance that IoT is using
#
# Dependencies:
# - Core is installed
# - IoT is installed
#
apiVersion: masauto.ibm.com/v1alpha1
kind: Monitor
metadata:
  name: masauto-monitor
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.9.x"
