# Adds Assist latest release to an existing MAS Core 8.8.x + IoT 8.5.x installation
#
# Assist will be configured to use the same db2 instance that IoT is using
#
# Dependencies:
# - Core is installed
# - IoT is installed
#
apiVersion: masauto.ibm.com/v1alpha1
kind: Assist
metadata:
  name: masauto-assist
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.8.x"
  cpd_product_version: "4.0.9"
  cos_type: "ocs"
  