apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: masauto-operator-system-operator-group
  namespace: masauto-operator-system
spec:
  targetNamespaces:
    - masauto-operator-system
