apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ecosystem-engineering-catalog
  namespace: openshift-marketplace
spec:
  displayName: ecosystem-engineering-catalog
  publisher: IBM
  sourceType: grpc
  image: quay.io/cloudnativetoolkit/ecosysengineer-catalog:v0.4.2
  updateStrategy:
    registryPoll:
      interval: 90m