# Adds Predict latest release to an existing MAS v8.9.x installation
#
# Predict will be deployed and configured. Note this app has several dependencies
#
# Dependencies:
# - CP4D Foundation
# - CP4D Services: wsl, wml, spark, aiopenscale
# - Maximo Monitor
# - Maximo Health
#
apiVersion: masauto.ibm.com/v1alpha1
kind: Predict
metadata:
  name: masauto-predict
  namespace: masauto-operator-system
annotations:
  ansible.operator-sdk/reconcile-period: "0s"  
spec:
  ibm_entitlement_secret: "ibm-entitlement-key" #secret where your ibm-entitlement-key is stored in operator namespace  
  mas_instance_id: "inst1"
  mas_workspace_id: "masdev"
  mas_app_channel: "8.7.x"
  cpd_product_version: "4.5.0"
  cpd_url: "<https:// ... insert your cp4d_url>"

## this cr assumes you have been using the defaults of this automation
## and in the masconfig dir you have a wsl project yaml and project id 
## file already created.  If so nothing else is needed.  If you did NOT take
## the defaults used in this automation then you will need to define the following
## variables as well:
##
## cpd_ws_project_name: "" ## value found in cp4d ui projects location
## cpd_ws_project_id: "" ## value found in cp4d url, open the ws project, id is number after the "project" in the url
