---
# Source: mas-manage/templates/mas-manage.yaml
# Add Manage latest application to an existing MAS Core 8.10.x installation
#
# Dependencies:
# - Core
#
apiVersion: masauto.ibm.com/v1alpha1
kind: Manage
metadata:
  name: masauto-manage
  annotations:
    ansible.operator-sdk/reconcile-period: "0s"
    argocd.argoproj.io/sync-wave: "5"
    helm.sh/hook-weight: "5"
  labels:
    helm.sh/chart: mas-manage-0.1.0
    app.kubernetes.io/name: mas-manage
    app.kubernetes.io/instance: mas-manage
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  # secret where your ibm-entitlement-key is stored in operator namespace
  ibm_entitlement_secret: ibm-entitlement-key
  mas_instance_id: inst1
  mas_workspace_id: masdev
  mas_app_id: manage
  mas_app_channel: "8.6.x"
  # recommend keeping db for manage at workspace-application scope by default
  mas_config_scope: wsapp
  mas_appws_bindings_jdbc: workspace-application

  mas_app_settings_demodata: "true"
  mas_appws_components:
    base:
      version: latest
    health:
      version: latest
  configure_external_db: "true"
  ssl_enabled: true

  db_instance_id: db2w-manage
  mas_jdbc_user: db2inst1
  mas_jdbc_password_secret: manage-jdbc-credentials
  ##  mas_jdbc_url: the jdbc url for the existing DB that will be used for MAS Manage
  ##
  ##  == Samples ==
  ##  DB2:
  ##   mas_jdbc_url: "jdbc:db2://dbserverxx:50000/MANAGE"
  ##   mas_jdbc_url: "jdbc:db2://123.456.78.90:50001/MANAGE:sslConnection=true;sslVersion=TLSv1.2;"  if SSL enabled
  ##
  ##  Oracle:
  ##   mas_jdbc_url: "jdbc:oracle:thin:@dbserverxx:1521:maximo"
  ##
  ##  SQL Server:
  ##   mas_jdbc_url: "jdbc:sqlserver://;serverName=dbserverxx;portNumber=1433;databaseName=msdbxx;integratedSecurity=false;sendStringParametersAsUnicode=false;selectMethod=cursor;encrypt=false;trustServerCertificate=false;"
  ##   mas_jdbc_url: "jdbc:sqlserver://;serverName=dbserverxx;portNumber=1433;databaseName=msdbxx;integratedSecurity=false;sendStringParametersAsUnicode=false;selectMethod=cursor;encrypt=true;trustServerCertificate=true;" if SSL enabled
  mas_jdbc_url: mongodb://test

  mas_app_settings_db2_schema: MANAGE
  mas_app_settings_tablespace: MAXDATA
  mas_app_settings_indexspace: MAXINDEX
