{{- if .Values.ibm_entitlement_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mas.ibm_entitlement_secret" . }}
  namespace: {{ include "operator.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    helm.sh/hook-weight: "-10"
  labels:
    {{- include "masauto-operator.labels" . | nindent 4 }}
stringData:
  username: cp
  password: {{ .Values.ibm_entitlement_key }}
{{- end }}
