# Default values for masauto-manage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ibm_entitlement_secret: ""
  mas_instance_id: ""
  mas_workspace_id: ""
  operator_namespace: ""

## Required values
ibm_entitlement_secret: ""
mas_instance_id: ""
mas_workspace_id: ""
operator_namespace: ""

mas_app_channel: "8.6.x"
mas_config_scope: "wsapp"
mas_appws_bindings_jdbc: "workspace-application"

mas_app_settings_demodata: true

database:
  external: false
  db2_instance_name: "db2w-manage"
  db2_dbname: "MANAGE"
  db2_meta_storage_class: ""
  db2_data_storage_class: ""

  ssl_enabled: true
  db_pem_configmap: ""
  mas_jdbc_user: ""
  mas_jdbc_password_secret: ""
  mas_jdbc_url: ""

  db2_schema: ""
  tablespace: ""
  indexspace: ""
