{{- if .Values.masLicense.secretName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mas-core.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
  {{- include "mas-core.labels" . | nindent 4 }}
