# Adds AppConnect to an existing MAS Core 8.8.x
#
# Dependencies:
# - Core is installed
#
- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - community.general
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Cluster-wide dependencies for MAS 
    ibm_entitlement_key: "{{ ibm_entitlement_key }}"

    # Entitlement key can be passed by either the key or a secret name
    ibm_entitlement_secret: "{{ ibm_entitlement_secret }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - appconnect_storage_class is defined and appconnect_storage_class != ""
          - appconnect_channel is defined and appconnect_channel != ""
          - appconnect_dashboard_name is defined and appconnect_dashboard_name != ""
          - appconnect_license_id is defined and appconnect_license_id != ""
          - appconnect_namespace is defined and appconnect_namespace != ""
          - mas_instance_id is defined and mas_instance_id != ""
        fail_msg: "One or more required variables are not defined"

    # Check if AppConnect is already installed first.
    - include_tasks: "{{ playbook_dir }}/../tasks/preinstall_check_appcon.yml"

    # Lookup entitlement key via secret if it's declared and the ibm_entitlement_key isn't
    - include_tasks: "{{ playbook_dir }}/../tasks/lookup_entitlement.yml"

    - name: "Ensure entitlement is there"
      assert:
        that:
          - ibm_entitlement_key is defined and ibm_entitlement_key != ""
        fail_msg: "Entitlement key not defined"

    # Create masconfig directory based on instance_id
    - include_tasks: "{{ playbook_dir }}/../tasks/masconfig_setup.yml"         

  roles:
    - role: ibm.mas_devops.appconnect
      vars:
        appconnect_entitlement_key: "{{ ibm_entitlement_key }}"
        # For AppConnect - these defaults are for a MAS v8.8 install and should be used for a v8.8 install core
        appconnect_channel: "{{ appconnect_channel }}"
        appconnect_dashboard_name: "{{ appconnect_dashboard_name }}"
        appconnect_license_id: "{{ appconnect_license_id }}"
        appconnect_storage_class: "{{ appconnect_storage_class }}" #file storage class

