# Adds CP4D to an existing MAS Core 8.8.x
#
# Dependencies:
# - Core is installed
#
- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - community.general
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Cluster-wide dependencies for MAS 
    ibm_entitlement_key: "{{ ibm_entitlement_key }}"
    mas_config_dir: "~/masconfig"
    mas_instance_id: "{{ mas_instance_id }}"

    # Entitlement key can be passed by either the key or a secret name
    ibm_entitlement_secret: "{{ ibm_entitlement_secret }}"

    install_cp4d_platform: "{{ install_cp4d_platform }}"
    install_watson_studio: "{{ install_watson_studio }}"
    install_watson_machine_learning: "{{ install_watson_machine_learning }}"
    install_analytics_engine: "{{ install_analytics_engine }}"
    install_watson_openscale: "{{ install_watson_openscale }}"
    install_watson_discovery: "{{ install_watson_discovery }}"

    cpd_primary_storage_class: "{{ cpd_primary_storage_class }}" # file
    cpd_metadata_storage_class: "{{ cpd_metadata_storage_class }}" # block
    cpd_product_version: "{{ lookup('env', 'cpd_product_version') | default('4.0.9', true) }}"
    cpd_instance_namespace: "{{ lookup('env', 'cpd_instance_namespace') | default('ibm-cpd', true) }}"

  pre_tasks:
    # Check for current install of CP4D components
    - name: "Check for existing CP4D Foundation"
      when: (install_cp4d_platform|bool) and
            not (install_watson_studio|bool) and
            not (install_watson_machine_learning|bool) and
            not (install_analytics_engine|bool) and
            not (install_watson_openscale|bool) and
            not (install_watson_discovery|bool)
      kubernetes.core.k8s_info:
        api_version: zen.cpd.ibm.com/v1
        name: lite-cr
        namespace: "{{ cpd_instance_namespace }}"
        kind: ZenService
      register: op_zenservice_lookup

    - name: "Check if CP4D Foundation is already in completed state"
      when: (op_zenservice_lookup.resources[0].status.zenStatus is defined) and
            (op_zenservice_lookup.resources[0].status.zenStatus == "Completed")
      meta: end_play  

    # Lookup entitlement key via secret if it's declared and the ibm_entitlement_key isn't
    - name: "Lookup IBM Entitlement Key credentials"
      when: (ibm_entitlement_secret is defined and ibm_entitlement_secret != "")
      ignore_errors: true      
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ ibm_entitlement_secret }}"
        namespace: "masauto-operator-system"
      register: entitlement_credentials 
    
    - name: "Set entitllement based on secret"
      when: (entitlement_credentials.api_found) and
            (ibm_entitlement_secret is defined and ibm_entitlement_secret != "")
      ignore_errors: true
      set_fact:
        ibm_entitlement_key: "{{ entitlement_credentials.resources[0].data.password | b64decode }}"
    
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - ibm_entitlement_key is defined and ibm_entitlement_key != ""
        fail_msg: "One or more required variables are not defined"

  roles:
    # Cloud Pak for Data Platform (~1 1/2 hours)
    - role: ibm.mas_devops.ibm_catalogs
      when: install_cp4d_platform|bool
    - role: ibm.mas_devops.common_services
      when: install_cp4d_platform|bool
    - role: ibm.mas_devops.cp4d
      when: install_cp4d_platform|bool

    # Watson Studio (~3 hours)
    - role: ibm.mas_devops.cp4d_service
      when: install_watson_studio|bool
      vars:
        cpd_service_name: wsl

    # Watson Machine Learning (~2 1/2 hours)
    - role: ibm.mas_devops.cp4d_service
      when: install_watson_machine_learning|bool
      vars:
        cpd_service_name: wml

    # Analytics Engine Powered by Apache Spark (~30 minutes)
    - role: ibm.mas_devops.cp4d_service
      when: install_analytics_engine|bool
      vars:
        cpd_service_name: spark

    # Watson OpenScale (~1 hour)
    - role: ibm.mas_devops.cp4d_service
      when: install_watson_openscale|bool
      vars:
        cpd_service_name: aiopenscale

    # Watson Discovery (~1 hour)
    - role: ibm.mas_devops.cp4d_service
      when: install_watson_discovery|bool
      vars:
        cpd_service_name: wd

    - role: ibm.mas_devops.suite_config
    