- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Cluster-wide dependencies for MAS 
    mas_config_dir: "~/masconfig"
    ibm_entitlement_key: "{{ ibm_entitlement_key }}"
    mas_instance_id: "{{ mas_instance_id }}"
    
    
    # Application Dependencies
    db2_instance_name: "{{ db2_instance_name | default('db2w-shared', true) }}"

    # Application Installation
    # mas_app_id can be set to "health" to install manage in the "Health standalone" mode from this same playbook.
    mas_app_id: "{{ mas_app_id | default('manage', true) }}"
    mas_app_channel: "{{ mas_app_channel | default('8.4.x', true) }}"

    # Application Configuration
    mas_workspace_id: "{{ mas_workspace_id | default('masdev', true) }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - ibm_entitlement_key != ""
          - mas_instance_id != ""
        fail_msg: "One or more required variables are not defined"

  roles:
    - role: ibm.mas_devops.db2
      vars:
        db2_instance_name: "{{ db2_instance_name }}"
        db2_meta_storage_class: "{{ db2_meta_storage_class }}" #file storage class
        db2_data_storage_class: "{{ db2_data_storage_class }}" #block storage class
    - role: ibm.mas_devops.suite_db2_setup_for_manage
    
    - role: ibm.mas_devops.suite_config
    - role: ibm.mas_devops.suite_app_install
    - role: ibm.mas_devops.suite_app_config
