# Adds Monitor latest release to an existing MAS Core 8.8.x + IoT 8.5.x installation
#
# Monitor will be configured to use the same db2 instance that IoT is using
#
- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - community.general
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Application Installation
    mas_app_id: monitor
    mas_app_channel: "{{ mas_app_channel | default('8.8.x') }}"

    # Application Configuration
    mas_workspace_id: "{{ mas_workspace_id | default('masdev') }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - ibm_entitlement_key is defined and ibm_entitlement_key != ""
          - mas_instance_id is defined and mas_instance_id != ""
        fail_msg: "One or more required variables are not defined"

  roles:
    - role: ibm.mas_devops.suite_app_install
      vars:
        mas_entitlement_key: "{{ ibm_entitlement_key }}"
    - role: ibm.mas_devops.suite_app_config
