# Adds Optimizer latest release to an existing MAS Core 8.9.x installation
#
#
# Dependencies:
# - Core is installed
#
- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - community.general
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Cluster-wide dependencies for MAS 
    ibm_entitlement_key: "{{ ibm_entitlement_key }}"
    
    # Application Installation
    mas_app_id: optimizer
    mas_app_channel: "{{ mas_app_channel }}"
    
    # Application Configuration
    mas_workspace_id: "{{ mas_workspace_id }}"

    # Entitlement key can be passed by either the key or a secret name
    ibm_entitlement_secret: "{{ ibm_entitlement_secret }}"

    # Application specific config
    mas_app_plan: "{{ mas_app_plan }}"
    
  pre_tasks:
    # Check if optimizer is already installed first.
    - include_tasks: "{{ playbook_dir }}/../tasks/preinstall_check_optimizer.yml"

    # Lookup entitlement key via secret if it's declared and the ibm_entitlement_key isn't
    - include_tasks: "{{ playbook_dir }}/../tasks/lookup_entitlement.yml"

    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - ibm_entitlement_key is defined and ibm_entitlement_key != ""
          - mas_app_channel is defined and mas_app_channel != ""
          - mas_instance_id is defined and mas_instance_id != ""
        fail_msg: "One or more required variables are not defined"

    # Create masconfig directory based on instance_id
    - include_tasks: "{{ playbook_dir }}/../tasks/masconfig_setup.yml" 

  roles:
    - role: ibm.mas_devops.suite_app_install
      vars:
        mas_entitlement_key: "{{ ibm_entitlement_key }}"
        mas_app_plan: "{{ mas_app_plan }}"
    - role: ibm.mas_devops.suite_app_config