# Adds Predict latest release to an existing MAS v8.9.x installation
#
# Predict will be deployed and configured. Note this app has several dependencies
#
# Dependencies:
# - CP4D Foundation
# - CP4D Services: wsl, wml, spark, aiopenscale, spss (as of mas v8.10)
# - Maximo Monitor
# - Maximo Health
#
- hosts: localhost
  any_errors_fatal: true
  collections:
    - community.kubernetes
    - community.general
    - operator_sdk.util
    - kubernetes.core
    - ibm.mas_devops
    - ibm.cloudcollection

  vars:
    # Cluster-wide dependencies for MAS 
    mas_config_dir: "~/masconfig"
    ibm_entitlement_key: "{{ ibm_entitlement_key }}"
    mas_instance_id: "{{ mas_instance_id }}"
    
    # Application Installation
    mas_app_id: predict
    mas_app_channel: "{{ mas_app_channel }}"

    # Application Configuration
    mas_workspace_id: "{{ mas_workspace_id }}"

    # Entitlement key can be passed by either the key or a secret name
    ibm_entitlement_secret: "{{ ibm_entitlement_secret }}"
    
  pre_tasks:
    # Check if Predict is already installed first.
    - include_tasks: "{{ playbook_dir }}/../tasks/preinstall_check_predict.yml"

    # Lookup entitlement key via secret if it's declared and the ibm_entitlement_key isn't
    - include_tasks: "{{ playbook_dir }}/../tasks/lookup_entitlement.yml"

    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - ibm_entitlement_key is defined and ibm_entitlement_key != ""
          - mas_app_channel is defined and mas_app_channel != ""
          - cpd_url is defined and cpd_url != ""
          - cpd_product_version is defined and cpd_product_version != ""
        fail_msg: "One or more required variables are not defined"

  roles:
    # run the suite config incase a dependency was installed and didn't get configured yet
    - role: ibm.mas_devops.gencfg_watsonstudio
    - role: ibm.mas_devops.suite_config
    - role: ibm.mas_devops.suite_app_install
      vars:
        mas_entitlement_key: "{{ ibm_entitlement_key }}"
    - role: ibm.mas_devops.suite_app_config
      vars:   
        cpd_url: "{{ cpd_url }}"
        cpd_product_version: "{{ cpd_product_version }}"
