{{- if and .Values.masLicense.hostId .Values.masLicense.licenseKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.masLicense.secretName }}
stringData:
  licensingId: {{ .Values.masLicense.hostId }}
  licensingKey: {{ .Values.masLicense.licenseKey }}
{{- end }}
