{{- if and .Values.masLicense.serviceAccount.create .Values.masLicense.secretName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mas-core.serviceAccountName" . }}
  namespace: {{ include "operator.namespace" . }}
  labels:
{{- include "mas-core.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    helm.sh/hook-weight: "-100"
{{- with .Values.masLicense.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
